version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/:/etc/mysql/conf.d/
      - /data/mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootkye
      MYSQL_DATABASE: confluence
      MYSQL_USER: confluence
      MYSQL_PASSWORD: confluencekye
  confluence:
    image: atlassian/confluence-server
    ports:
      - "8090:8090"
    volumes:
      - /data/confluence:/var/atlassian/application-data/confluence
