version: '2.2'
services:
  kibana:
    image: registry.cn-shenzhen.aliyuncs.com/kye/kibana:6.2.4
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 80:5601
    networks:
      - esnet
  logstash:
    image: registry.cn-shenzhen.aliyuncs.com/kye/logstash:6.2.4
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
    #ports:
     # - 80:5601
    networks:
      - esnet
  elasticsearch:
    image: registry.cn-shenzhen.aliyuncs.com/kye/elasticsearch-platinum:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: registry.cn-shenzhen.aliyuncs.com/kye/elasticsearch-platinum:6.2.4
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet


volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
