server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
elasticsearch.username: elastic
elasticsearch.password: abcd1234*
xpack.monitoring.ui.container.elasticsearch.enabled: true
